name: fastly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  repository_dispatch:
    types: [download]
jobs:
  automate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DST_SSH_KEY }}
      - uses: actions/checkout@v4
      - name: run
        env:
          REMOTE_JOB: ${{ github.event.client_payload.job || secrets.REMOTE_JOB }}
          REMOTE_TOKEN: ${{ github.event.client_payload.token || secrets.REMOTE_TOKEN }}
        run: |
          set -e
          echo "::add-mask::${REMOTE_JOB}"
          echo "::add-mask::${REMOTE_TOKEN}"

          echo [$(date "+%Y-%m-%d %H:%M:%S")] "Init..."
          pip install --disable-pip-version-check -q -r requirements.txt

          echo [$(date "+%Y-%m-%d %H:%M:%S")] "Download..."
          flask download --remote ${REMOTE_JOB} \
                        --token ${REMOTE_TOKEN}

          echo [$(date "+%Y-%m-%d %H:%M:%S")] "Done."
