name: worker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  repository_dispatch:
    types: [fastly, gfw]
jobs:
  automate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DST_SSH_KEY }}
      - run: pip install -r requirements.txt
      # REF: https://github.com/actions/runner/issues/643#issuecomment-823537871
      - run: |
          INP_JOB=$(jq -r '.client_payload.job' $GITHUB_EVENT_PATH)
          INP_TOKEN=$(jq -r '.client_payload.token' $GITHUB_EVENT_PATH)
          echo "::add-mask::$INP_JOB"
          echo "::add-mask::$INP_TOKEN"
      - name: run
        env:
          REMOTE_JOB: ${{ github.event.client_payload.job || secrets.REMOTE_JOB }}
          REMOTE_TOKEN: ${{ github.event.client_payload.token || secrets.REMOTE_TOKEN }}
        run: |
          set -e

          echo [$(date "+%Y-%m-%d %H:%M:%S")] "Download..."
          flask download --remote ${REMOTE_JOB} \
                        --token ${REMOTE_TOKEN}

          echo [$(date "+%Y-%m-%d %H:%M:%S")] "Done."
